### ISSUE TITLE
일부 디렉토리 정리했으면 좋겠습니다

### ISSUE THREAD

**Issue by jacking75** [pdpdds/CGSFII#1]
이제 꽤 만이 진행된 것 같은데 일부 디렉토리 정리했으면 좋겠습니다^^;
Bin32와 Bin64는 Bin 디렉토리 안으로 넣고, 
Shared와 Sample.sln은 Example 디렉토리 안으로 들어가면 
프로젝트가 깔끔 할 것 같습니다.

**Comment by pdpdds** [comment]
32비트는 아예 삭제해 버릴까요? ^^

**Comment by jacking75** [comment]
네 저는 32비트 삭제 찬성입니다  이젠 서버에서는 32비트는 의미 없다고 봅니다 ^^

**Comment by pdpdds** [comment]
정리 완료했습니다 ^^
