### ISSUE TITLE
ExampleNet 디렉토리도 이름을 좀 더 알맞게 바꾸어보죠^^

### ISSUE THREAD

**Issue by jacking75** [pdpdds/CGSFII#2]
ExampleNet 디렉토리에는 닷넷버전과 예제 샘플이 같이 있으니 디렉토리 이름을 
DotCGSF 이라고 하면 어떨까요?^^
(이름은 Netty를 닷넷버전으로 포팅하는 프로젝트의 이름(DotNetty)에서 따왔습니다)

디렉토리 이름은 더 좋은 것이 있으면 다른 것으로 해도 좋습니다^^

**Comment by pdpdds** [comment]
정리완료. 이렇께까지 했으니 닷넷버전 강화좀 해주세요 ^^ 괜찮으면 바로 지금 개발하는 서버에 써먹어 보겠습니다 ㅎㅎ

**Comment by jacking75** [comment]
넵 늦어도 5월부터는(다음주는 NDC가 있어서^^;) 저도 본격적으로 개발 들어가겠습니다.
